apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: dmilan/mytestpython:v3
            # args:
            # - python
            # - app/main.py
          restartPolicy: OnFailure